name: Publish @typebot.io/js package to NPM

on:
  push:
    tags:
      - 'js-v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v1
      - run: bun i --frozen-lockfile
      - run: bun turbo build --filter=@typebot.io/js...
      - run: cd packages/embeds/js && bun publish --no-git-checks --access public
